config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  resources :blog_posts

  # Defines the root path route ("/")
  root 'blog_posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
# frozen_string_literal: true

class BlogPost < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
# frozen_string_literal: true

class BlogPostsController < ApplicationController
  before_action :set_blog_post, except: %i[index new create]

  def index
    @blog_posts = BlogPost.order(:id)
  end

  def show; end

  def new
    @blog_post = BlogPost.new
  end

  def create
    @blog_post = BlogPost.new(blog_post_params)

    if @blog_post.save
      redirect_to @blog_post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @blog_post.update(blog_post_params)
      redirect_to @blog_post
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @blog_post.destroy
    redirect_to root_path
  end

  private

  def blog_post_params
    params.require(:blog_post).permit(:title, :body)
  end

  def set_blog_post
    @blog_post = BlogPost.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blog_posts/_form.html.erb
<%= form_with model: blog_post do |form| %>
  <% if form.object.errors.any? %>
    <div>
      <% form.object.errors.full_messages.each do |message| %>
        <p><%= message%></p>
      <% end %>
    </div>
  <% end %>
  
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <%= form.button %>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>Edit Blog Post</h1>

<%= render partial: "form", locals: { blog_post: @blog_post} %>
<%= button_to "Delete Post", @blog_post, method: :delete, data: { turbo_confirm: "Are you sure?" } %>

app/views/blog_posts/index.html.erb
<h1>My Blog</h1>
<% @blog_posts.each do |blog_post| %>
  <!-- <h2><%= link_to blog_post.title, "/posts/#{blog_post.id}"%></h2> -->
  <!-- <h2><%= link_to blog_post.title, blog_post_path(blog_post)%></h2> -->
  <%# The above 2 lines and the following line is equivalent. This works because of as: :blog_post in route file %>
  <h2><%= link_to blog_post.title, blog_post%></h2>
  <p><%= blog_post.body%></p>
<% end %>

app/views/blog_posts/new.html.erb
<h1>New Blog Post</h1>

<%= render partial: "form", locals: { blog_post: @blog_post} %>

app/views/blog_posts/show.html.erb
<h1><%= @blog_post.title%></h1>
<p><%= @blog_post.body%></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div>
      <% if user_signed_in? %>
        <%= link_to "User Profile", edit_user_registration_path %>
        <%= button_to "Log out", destroy_user_session_path, method: :delete %>
      <%else%>
        <%= link_to "Login", new_user_session_path %>
        <%= link_to "Sign up", new_user_registration_path %>
      <% end %>
    </div>

    <%= yield %>
  </body>
</html>